
export  const CAROUSEL_IMAGE_REQUEST="CAROUSEL_IMAGE_REQUEST"
export  const CAROUSEL_IMAGE_SUCCESS="CAROUSEL_IMAGE_SUCCESS"
export  const CAROUSEL_IMAGE_FAILURE="CAROUSEL_IMAGE_FAILURE"

export  const GET_CAROUSEL_IMAGE_REQUEST="GET_CAROUSEL_IMAGE_REQUEST"
export  const GET_CAROUSEL_IMAGE_SUCCESS="GET_CAROUSEL_IMAGE_SUCCESS"
export  const GET_CAROUSEL_IMAGE_FAILURE="GET_CAROUSEL_IMAGE_FAILURE"